name: vKitPvP
version: '${project.version}'
main: it.thatskai.vanteykitpvp.VanteyKitPvP
depend:
  - PlaceholderAPI
commands:
  coinflip:
    aliases:
      - cf
  vkitpvp:
    aliases:
      - kitpvpreforged
  koth: