name: vKitPvP
version: '${project.version}'
main: it.thatskai.vanteykitpvp.VanteyKitPvP
commands:
  coinflip:
    aliases:
      - cf
  vkitpvp:
    aliases:
      - kitpvpreforged
  envoy:
  assegno:
    aliases:
      - assegni